# Generated by Django 4.2 on 2023-04-16 02:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_color_variant_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("coupon_code", models.CharField(max_length=10)),
                ("is_expired", models.BooleanField(default=False)),
                ("discount_price", models.IntegerField(default=100)),
                ("minimum_amount", models.IntegerField(default=500)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
